drop table ECXCANGE_RECORD if exists;

create table ECXCANGE_RECORD (
    DATE VARCHAR(10) NOT NULL,
    SELL_CURRENCY VARCHAR(3) NOT NULL,
    BUY_CURRENCY VARCHAR(3) NOT NULL,
    FX_RATES_RESPONSE TEXT NOT NULL,
    CONSTRAINT ID PRIMARY KEY (DATE, SELL_CURRENCY, BUY_CURRENCY)
);