drop table ARTICLE if exists;

create table ARTICLE (
    ID UUID PRIMARY KEY,
    TITLE TEXT NOT NULL,
    TEXT TEXT NOT NULL,
    CREATED TIMESTAMP WITH TIME ZONE,
    UPDATED TIMESTAMP WITH TIME ZONE
);