drop table ARTICLE if exists;
drop table AUTHOR if exists;

create table ARTICLE (
    ID UUID PRIMARY KEY,
    TITLE TEXT NOT NULL,
    TEXT TEXT NOT NULL,
    CREATED TIMESTAMP WITH TIME ZONE,
    UPDATED TIMESTAMP WITH TIME ZONE,
    AUTHOR_ID INT NOT NULL,
    CONSTRAINT FK_ARTICLE_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);

create table AUTHOR (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL
);